### ISSUE TITLE
The script called build failed with exit code 1

### ISSUE THREAD

**Issue by simran66** [sezna/nps#218]
- `nps` version: 5.9.12
- `node` version: 10.16.0
- `npm` version: 6.9.0

Scripts file (or at least the relevant bits):

The command executed:

```console
 npm run build
```

The output:
 cat /home/ec2-user/.npm/_logs/2020-03-03T03_09_45_612Z-debug.log

```console
0 info it worked if it ends with ok
1 verbose cli [ '/home/ec2-user/.nvm/versions/node/v10.16.0/bin/node',
1 verbose cli   '/home/ec2-user/.nvm/versions/node/v10.16.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle SpurtCommerce@3.0.0~prebuild: SpurtCommerce@3.0.0
6 info lifecycle SpurtCommerce@3.0.0~build: SpurtCommerce@3.0.0
7 verbose lifecycle SpurtCommerce@3.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle SpurtCommerce@3.0.0~build: PATH: /home/ec2-user/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ec2-user/hianfa2/api/node_modules/.bin:/home/ec2-user/.nvm/versions/node/v10.16.0/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin
9 verbose lifecycle SpurtCommerce@3.0.0~build: CWD: /home/ec2-user/hianfa2/api
10 silly lifecycle SpurtCommerce@3.0.0~build: Args: [ '-c', 'npm start build' ]
11 silly lifecycle SpurtCommerce@3.0.0~build: Returned: code: 1  signal: null
12 info lifecycle SpurtCommerce@3.0.0~build: Failed to exec build script
13 verbose stack Error: SpurtCommerce@3.0.0 build: `npm start build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid SpurtCommerce@3.0.0
15 verbose cwd /home/ec2-user/hianfa2/api
16 verbose Linux 4.9.70-25.242.amzn1.x86_64
17 verbose argv "/home/ec2-user/.nvm/versions/node/v10.16.0/bin/node" "/home/ec2-user/.nvm/versions/node/v10.16.0/bin/npm" "run" "build"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error SpurtCommerce@3.0.0 build: `npm start build`
22 error Exit status 1
23 error Failed at the SpurtCommerce@3.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Problem description:
npm install seem to have worked without any issues. I also installed and uninstalled npm modules but did not help. How can I fix this?

Suggested solution:

**Comment by sezna** [comment]
Can you post the contents of your `package.json`? This issue doesn't look to involve `nps` at first glance.
